# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created: Mon May 27 22:56:42 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(887, 650)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabIgWidget = QtGui.QTabWidget(self.widget)
        self.tabIgWidget.setEnabled(True)
        self.tabIgWidget.setObjectName(_fromUtf8("tabIgWidget"))
        self.tabRegions = QtGui.QWidget()
        self.tabRegions.setEnabled(False)
        self.tabRegions.setObjectName(_fromUtf8("tabRegions"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabRegions)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.tableFR1 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFR1.sizePolicy().hasHeightForWidth())
        self.tableFR1.setSizePolicy(sizePolicy)
        self.tableFR1.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableFR1.setFont(font)
        self.tableFR1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR1.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableFR1.setShowGrid(False)
        self.tableFR1.setRowCount(0)
        self.tableFR1.setObjectName(_fromUtf8("tableFR1"))
        self.tableFR1.setColumnCount(0)
        self.tableFR1.horizontalHeader().setVisible(False)
        self.tableFR1.horizontalHeader().setDefaultSectionSize(10)
        self.tableFR1.horizontalHeader().setHighlightSections(False)
        self.tableFR1.horizontalHeader().setMinimumSectionSize(10)
        self.tableFR1.verticalHeader().setVisible(False)
        self.tableFR1.verticalHeader().setDefaultSectionSize(10)
        self.tableFR1.verticalHeader().setHighlightSections(False)
        self.tableFR1.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_8.addWidget(self.tableFR1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLineWidth(1)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.tableFR2 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFR2.sizePolicy().hasHeightForWidth())
        self.tableFR2.setSizePolicy(sizePolicy)
        self.tableFR2.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableFR2.setFont(font)
        self.tableFR2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableFR2.setShowGrid(False)
        self.tableFR2.setRowCount(0)
        self.tableFR2.setObjectName(_fromUtf8("tableFR2"))
        self.tableFR2.setColumnCount(0)
        self.tableFR2.horizontalHeader().setVisible(False)
        self.tableFR2.horizontalHeader().setDefaultSectionSize(10)
        self.tableFR2.horizontalHeader().setHighlightSections(False)
        self.tableFR2.horizontalHeader().setMinimumSectionSize(10)
        self.tableFR2.verticalHeader().setVisible(False)
        self.tableFR2.verticalHeader().setDefaultSectionSize(10)
        self.tableFR2.verticalHeader().setHighlightSections(False)
        self.tableFR2.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_8.addWidget(self.tableFR2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.tableFR3 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFR3.sizePolicy().hasHeightForWidth())
        self.tableFR3.setSizePolicy(sizePolicy)
        self.tableFR3.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableFR3.setFont(font)
        self.tableFR3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableFR3.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableFR3.setShowGrid(False)
        self.tableFR3.setRowCount(0)
        self.tableFR3.setObjectName(_fromUtf8("tableFR3"))
        self.tableFR3.setColumnCount(0)
        self.tableFR3.horizontalHeader().setVisible(False)
        self.tableFR3.horizontalHeader().setDefaultSectionSize(10)
        self.tableFR3.horizontalHeader().setHighlightSections(False)
        self.tableFR3.horizontalHeader().setMinimumSectionSize(10)
        self.tableFR3.verticalHeader().setVisible(False)
        self.tableFR3.verticalHeader().setDefaultSectionSize(10)
        self.tableFR3.verticalHeader().setHighlightSections(False)
        self.tableFR3.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_8.addWidget(self.tableFR3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.label_8 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLineWidth(1)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.tableCDR1 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCDR1.sizePolicy().hasHeightForWidth())
        self.tableCDR1.setSizePolicy(sizePolicy)
        self.tableCDR1.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableCDR1.setFont(font)
        self.tableCDR1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR1.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableCDR1.setShowGrid(False)
        self.tableCDR1.setRowCount(0)
        self.tableCDR1.setObjectName(_fromUtf8("tableCDR1"))
        self.tableCDR1.setColumnCount(0)
        self.tableCDR1.horizontalHeader().setVisible(False)
        self.tableCDR1.horizontalHeader().setDefaultSectionSize(10)
        self.tableCDR1.horizontalHeader().setHighlightSections(False)
        self.tableCDR1.horizontalHeader().setMinimumSectionSize(10)
        self.tableCDR1.verticalHeader().setVisible(False)
        self.tableCDR1.verticalHeader().setDefaultSectionSize(10)
        self.tableCDR1.verticalHeader().setHighlightSections(False)
        self.tableCDR1.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_9.addWidget(self.tableCDR1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.label_6 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_9.addWidget(self.label_6)
        self.tableCDR2 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCDR2.sizePolicy().hasHeightForWidth())
        self.tableCDR2.setSizePolicy(sizePolicy)
        self.tableCDR2.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableCDR2.setFont(font)
        self.tableCDR2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableCDR2.setShowGrid(False)
        self.tableCDR2.setRowCount(0)
        self.tableCDR2.setObjectName(_fromUtf8("tableCDR2"))
        self.tableCDR2.setColumnCount(0)
        self.tableCDR2.horizontalHeader().setVisible(False)
        self.tableCDR2.horizontalHeader().setDefaultSectionSize(10)
        self.tableCDR2.horizontalHeader().setHighlightSections(False)
        self.tableCDR2.horizontalHeader().setMinimumSectionSize(10)
        self.tableCDR2.verticalHeader().setVisible(False)
        self.tableCDR2.verticalHeader().setDefaultSectionSize(10)
        self.tableCDR2.verticalHeader().setHighlightSections(False)
        self.tableCDR2.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_9.addWidget(self.tableCDR2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.label_4 = QtGui.QLabel(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLineWidth(1)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_9.addWidget(self.label_4)
        self.tableCDR3 = QtGui.QTableWidget(self.tabRegions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCDR3.sizePolicy().hasHeightForWidth())
        self.tableCDR3.setSizePolicy(sizePolicy)
        self.tableCDR3.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.tableCDR3.setFont(font)
        self.tableCDR3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCDR3.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableCDR3.setShowGrid(False)
        self.tableCDR3.setRowCount(0)
        self.tableCDR3.setObjectName(_fromUtf8("tableCDR3"))
        self.tableCDR3.setColumnCount(0)
        self.tableCDR3.horizontalHeader().setVisible(False)
        self.tableCDR3.horizontalHeader().setDefaultSectionSize(10)
        self.tableCDR3.horizontalHeader().setHighlightSections(False)
        self.tableCDR3.horizontalHeader().setMinimumSectionSize(10)
        self.tableCDR3.verticalHeader().setVisible(False)
        self.tableCDR3.verticalHeader().setDefaultSectionSize(10)
        self.tableCDR3.verticalHeader().setHighlightSections(False)
        self.tableCDR3.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_9.addWidget(self.tableCDR3)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.tabIgWidget.addTab(self.tabRegions, _fromUtf8(""))
        self.tabHomologs = QtGui.QWidget()
        self.tabHomologs.setEnabled(False)
        self.tabHomologs.setObjectName(_fromUtf8("tabHomologs"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabHomologs)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tableDomain = QtGui.QTableWidget(self.tabHomologs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableDomain.sizePolicy().hasHeightForWidth())
        self.tableDomain.setSizePolicy(sizePolicy)
        self.tableDomain.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableDomain.setFont(font)
        self.tableDomain.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDomain.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDomain.setShowGrid(False)
        self.tableDomain.setWordWrap(False)
        self.tableDomain.setObjectName(_fromUtf8("tableDomain"))
        self.tableDomain.setColumnCount(0)
        self.tableDomain.setRowCount(0)
        self.tableDomain.horizontalHeader().setVisible(False)
        self.tableDomain.horizontalHeader().setDefaultSectionSize(10)
        self.tableDomain.horizontalHeader().setHighlightSections(False)
        self.tableDomain.horizontalHeader().setMinimumSectionSize(10)
        self.tableDomain.verticalHeader().setVisible(False)
        self.tableDomain.verticalHeader().setDefaultSectionSize(10)
        self.tableDomain.verticalHeader().setHighlightSections(False)
        self.tableDomain.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_10.addWidget(self.tableDomain)
        self.label_9 = QtGui.QLabel(self.tabHomologs)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.tableGermlines = QtGui.QTableWidget(self.tabHomologs)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableGermlines.setFont(font)
        self.tableGermlines.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableGermlines.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableGermlines.setShowGrid(False)
        self.tableGermlines.setWordWrap(False)
        self.tableGermlines.setObjectName(_fromUtf8("tableGermlines"))
        self.tableGermlines.setColumnCount(0)
        self.tableGermlines.setRowCount(0)
        self.tableGermlines.horizontalHeader().setVisible(False)
        self.tableGermlines.horizontalHeader().setDefaultSectionSize(10)
        self.tableGermlines.horizontalHeader().setHighlightSections(False)
        self.tableGermlines.horizontalHeader().setMinimumSectionSize(10)
        self.tableGermlines.verticalHeader().setVisible(False)
        self.tableGermlines.verticalHeader().setDefaultSectionSize(10)
        self.tableGermlines.verticalHeader().setHighlightSections(False)
        self.tableGermlines.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_10.addWidget(self.tableGermlines)
        self.label_10 = QtGui.QLabel(self.tabHomologs)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.tableHomologs = QtGui.QTableWidget(self.tabHomologs)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableHomologs.setFont(font)
        self.tableHomologs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHomologs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHomologs.setShowGrid(False)
        self.tableHomologs.setWordWrap(False)
        self.tableHomologs.setObjectName(_fromUtf8("tableHomologs"))
        self.tableHomologs.setColumnCount(0)
        self.tableHomologs.setRowCount(0)
        self.tableHomologs.horizontalHeader().setVisible(False)
        self.tableHomologs.horizontalHeader().setDefaultSectionSize(10)
        self.tableHomologs.horizontalHeader().setHighlightSections(False)
        self.tableHomologs.horizontalHeader().setMinimumSectionSize(10)
        self.tableHomologs.verticalHeader().setVisible(False)
        self.tableHomologs.verticalHeader().setDefaultSectionSize(10)
        self.tableHomologs.verticalHeader().setHighlightSections(False)
        self.tableHomologs.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_10.addWidget(self.tableHomologs)
        self.tabIgWidget.addTab(self.tabHomologs, _fromUtf8(""))
        self.tabHumanization = QtGui.QWidget()
        self.tabHumanization.setEnabled(False)
        self.tabHumanization.setObjectName(_fromUtf8("tabHumanization"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tabHumanization)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tableDomainHum = QtGui.QTableWidget(self.tabHumanization)
        self.tableDomainHum.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableDomainHum.setFont(font)
        self.tableDomainHum.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDomainHum.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDomainHum.setShowGrid(False)
        self.tableDomainHum.setWordWrap(False)
        self.tableDomainHum.setObjectName(_fromUtf8("tableDomainHum"))
        self.tableDomainHum.setColumnCount(0)
        self.tableDomainHum.setRowCount(0)
        self.tableDomainHum.horizontalHeader().setVisible(False)
        self.tableDomainHum.horizontalHeader().setDefaultSectionSize(10)
        self.tableDomainHum.horizontalHeader().setHighlightSections(False)
        self.tableDomainHum.horizontalHeader().setMinimumSectionSize(10)
        self.tableDomainHum.verticalHeader().setVisible(False)
        self.tableDomainHum.verticalHeader().setDefaultSectionSize(10)
        self.tableDomainHum.verticalHeader().setHighlightSections(False)
        self.tableDomainHum.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_11.addWidget(self.tableDomainHum)
        self.label_11 = QtGui.QLabel(self.tabHumanization)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_11.addWidget(self.label_11)
        self.tableHumanizations = QtGui.QTableWidget(self.tabHumanization)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableHumanizations.setFont(font)
        self.tableHumanizations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHumanizations.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHumanizations.setShowGrid(False)
        self.tableHumanizations.setWordWrap(False)
        self.tableHumanizations.setObjectName(_fromUtf8("tableHumanizations"))
        self.tableHumanizations.setColumnCount(0)
        self.tableHumanizations.setRowCount(0)
        self.tableHumanizations.horizontalHeader().setVisible(False)
        self.tableHumanizations.horizontalHeader().setDefaultSectionSize(10)
        self.tableHumanizations.horizontalHeader().setHighlightSections(False)
        self.tableHumanizations.horizontalHeader().setMinimumSectionSize(10)
        self.tableHumanizations.verticalHeader().setVisible(False)
        self.tableHumanizations.verticalHeader().setDefaultSectionSize(10)
        self.tableHumanizations.verticalHeader().setHighlightSections(False)
        self.tableHumanizations.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_11.addWidget(self.tableHumanizations)
        self.tabIgWidget.addTab(self.tabHumanization, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabIgWidget)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabInfoWidget = QtGui.QTabWidget(self.groupBox)
        self.tabInfoWidget.setEnabled(False)
        self.tabInfoWidget.setObjectName(_fromUtf8("tabInfoWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabInfo)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tabInfo)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineName = QtGui.QLineEdit(self.tabInfo)
        self.lineName.setEnabled(False)
        self.lineName.setMinimumSize(QtCore.QSize(100, 0))
        self.lineName.setReadOnly(True)
        self.lineName.setObjectName(_fromUtf8("lineName"))
        self.horizontalLayout_3.addWidget(self.lineName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tabInfo)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineSeq = QtGui.QLineEdit(self.tabInfo)
        self.lineSeq.setEnabled(False)
        self.lineSeq.setMinimumSize(QtCore.QSize(100, 0))
        self.lineSeq.setReadOnly(True)
        self.lineSeq.setObjectName(_fromUtf8("lineSeq"))
        self.horizontalLayout_4.addWidget(self.lineSeq)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tableAminoAcid = QtGui.QTableWidget(self.tabInfo)
        self.tableAminoAcid.setObjectName(_fromUtf8("tableAminoAcid"))
        self.tableAminoAcid.setColumnCount(7)
        self.tableAminoAcid.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableAminoAcid.setHorizontalHeaderItem(6, item)
        self.tableAminoAcid.verticalHeader().setVisible(True)
        self.tableAminoAcid.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_3.addWidget(self.tableAminoAcid)
        self.tabInfoWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabGraphics = QtGui.QWidget()
        self.tabGraphics.setObjectName(_fromUtf8("tabGraphics"))
        self.tabInfoWidget.addTab(self.tabGraphics, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabInfoWidget, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Q = QtGui.QMenu(self.menubar)
        self.menu_Q.setObjectName(_fromUtf8("menu_Q"))
        self.menuTool = QtGui.QMenu(self.menubar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        self.menuDomain_Model = QtGui.QMenu(self.menuTool)
        self.menuDomain_Model.setObjectName(_fromUtf8("menuDomain_Model"))
        self.menuHumanization_method = QtGui.QMenu(self.menuTool)
        self.menuHumanization_method.setObjectName(_fromUtf8("menuHumanization_method"))
        self.menuVew = QtGui.QMenu(self.menubar)
        self.menuVew.setObjectName(_fromUtf8("menuVew"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockSidePanel = QtGui.QDockWidget(MainWindow)
        self.dockSidePanel.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockSidePanel.setObjectName(_fromUtf8("dockSidePanel"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setDefaultSectionSize(60)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.butProc = QtGui.QPushButton(self.dockWidgetContents)
        self.butProc.setObjectName(_fromUtf8("butProc"))
        self.horizontalLayout_2.addWidget(self.butProc)
        self.butProcAll = QtGui.QPushButton(self.dockWidgetContents)
        self.butProcAll.setObjectName(_fromUtf8("butProcAll"))
        self.horizontalLayout_2.addWidget(self.butProcAll)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.dockSidePanel.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockSidePanel)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMouseTracking(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.actionCreate_report = QtGui.QAction(MainWindow)
        self.actionCreate_report.setObjectName(_fromUtf8("actionCreate_report"))
        self.action_Print = QtGui.QAction(MainWindow)
        self.action_Print.setObjectName(_fromUtf8("action_Print"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionConfigure_settings = QtGui.QAction(MainWindow)
        self.actionConfigure_settings.setObjectName(_fromUtf8("actionConfigure_settings"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionSave_FASTA = QtGui.QAction(MainWindow)
        self.actionSave_FASTA.setObjectName(_fromUtf8("actionSave_FASTA"))
        self.actionSide_panel = QtGui.QAction(MainWindow)
        self.actionSide_panel.setCheckable(True)
        self.actionSide_panel.setChecked(True)
        self.actionSide_panel.setObjectName(_fromUtf8("actionSide_panel"))
        self.actionToolbar = QtGui.QAction(MainWindow)
        self.actionToolbar.setCheckable(True)
        self.actionToolbar.setChecked(True)
        self.actionToolbar.setObjectName(_fromUtf8("actionToolbar"))
        self.actionKabat = QtGui.QAction(MainWindow)
        self.actionKabat.setCheckable(True)
        self.actionKabat.setObjectName(_fromUtf8("actionKabat"))
        self.actionIMGT = QtGui.QAction(MainWindow)
        self.actionIMGT.setCheckable(True)
        self.actionIMGT.setObjectName(_fromUtf8("actionIMGT"))
        self.actionHumanize = QtGui.QAction(MainWindow)
        self.actionHumanize.setObjectName(_fromUtf8("actionHumanize"))
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave_FASTA)
        self.menu_File.addAction(self.actionCreate_report)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Q.addAction(self.action_About)
        self.menu_Q.addAction(self.actionAbout_Qt)
        self.menu_Q.addAction(self.action_Help)
        self.menuDomain_Model.addSeparator()
        self.menuHumanization_method.addSeparator()
        self.menuTool.addAction(self.actionConfigure_settings)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.menuDomain_Model.menuAction())
        self.menuTool.addAction(self.actionRun)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.menuHumanization_method.menuAction())
        self.menuTool.addAction(self.actionHumanize)
        self.menuVew.addAction(self.actionSide_panel)
        self.menuVew.addAction(self.actionToolbar)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuVew.menuAction())
        self.menubar.addAction(self.menu_Q.menuAction())

        self.retranslateUi(MainWindow)
        self.tabIgWidget.setCurrentIndex(1)
        self.tabInfoWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dockSidePanel, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionSide_panel.setChecked)
        QtCore.QObject.connect(self.actionSide_panel, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockSidePanel.setVisible)
        QtCore.QObject.connect(self.toolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionToolbar.setChecked)
        QtCore.QObject.connect(self.actionToolbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.toolBar.setVisible)
        QtCore.QObject.connect(self.actionE_xit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "IgHumanizer v2", None))
        self.label_7.setText(_translate("MainWindow", "<b>FR1</b>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">FR2</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">FR3</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CDR1</span></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CDR2</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CDR3</span></p></body></html>", None))
        self.tabIgWidget.setTabText(self.tabIgWidget.indexOf(self.tabRegions), _translate("MainWindow", "&Regions", None))
        self.label_9.setText(_translate("MainWindow", "Germlines:", None))
        self.label_10.setText(_translate("MainWindow", "Homologs:", None))
        self.tabIgWidget.setTabText(self.tabIgWidget.indexOf(self.tabHomologs), _translate("MainWindow", "&Homologs", None))
        self.label_11.setText(_translate("MainWindow", "Humanizations:", None))
        self.tabIgWidget.setTabText(self.tabIgWidget.indexOf(self.tabHumanization), _translate("MainWindow", "Hu&manization", None))
        self.groupBox.setTitle(_translate("MainWindow", "Information", None))
        self.label.setText(_translate("MainWindow", "Name:", None))
        self.label_2.setText(_translate("MainWindow", "Seq:", None))
        item = self.tableAminoAcid.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AA", None))
        item = self.tableAminoAcid.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableAminoAcid.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Region", None))
        item = self.tableAminoAcid.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Germline AA", None))
        item = self.tableAminoAcid.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Homolog AA", None))
        item = self.tableAminoAcid.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Source AA", None))
        item = self.tableAminoAcid.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Homolog part", None))
        self.tabInfoWidget.setTabText(self.tabInfoWidget.indexOf(self.tabInfo), _translate("MainWindow", "&Info", None))
        self.tabInfoWidget.setTabText(self.tabInfoWidget.indexOf(self.tabGraphics), _translate("MainWindow", "&Graphics", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Q.setTitle(_translate("MainWindow", "?", None))
        self.menuTool.setTitle(_translate("MainWindow", "&Tools", None))
        self.menuDomain_Model.setTitle(_translate("MainWindow", "Domain Model", None))
        self.menuHumanization_method.setTitle(_translate("MainWindow", "Humanization &method", None))
        self.menuVew.setTitle(_translate("MainWindow", "Vew", None))
        self.dockSidePanel.setWindowTitle(_translate("MainWindow", "Side Panel", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Ig", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Seq", None))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "PTH", None))
        self.butProc.setText(_translate("MainWindow", "Process", None))
        self.butProcAll.setText(_translate("MainWindow", "Process all", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))
        self.action_Close.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionCreate_report.setText(_translate("MainWindow", "Create &report", None))
        self.actionCreate_report.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.action_Print.setText(_translate("MainWindow", "&Print", None))
        self.action_Print.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit", None))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_Help.setText(_translate("MainWindow", "&Help", None))
        self.action_Help.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))
        self.actionConfigure_settings.setText(_translate("MainWindow", "Configure &settings", None))
        self.actionRun.setText(_translate("MainWindow", "Run", None))
        self.actionRun.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionSave_FASTA.setText(_translate("MainWindow", "Save FASTA as...", None))
        self.actionSave_FASTA.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSide_panel.setText(_translate("MainWindow", "Side panel", None))
        self.actionToolbar.setText(_translate("MainWindow", "Toolbar", None))
        self.actionKabat.setText(_translate("MainWindow", "Kabat", None))
        self.actionIMGT.setText(_translate("MainWindow", "IMGT", None))
        self.actionHumanize.setText(_translate("MainWindow", "Humanize", None))

